dataset:
  test_size: 0.2
  val_size: 0.1
  random_state: 42
preprocessing:
  handle_missing: mean  # options: mean, median, drop
  outlier_threshold: 3  # Z-score threshold
  scaler: standard      # options: standard, minmax, robust
feature_engineering:
  polynomial_features: true
  degree: 2
  interaction_only: false
  feature_selection: true
  n_features_to_select: 10
